### ISSUE TITLE
Support with iPhone 6

### ISSUE THREAD

**Issue by guptatarun84** [pcentieiro/midian#3]
hi,

Just want to make sure if this still have supports for iPhone 6. What changes needs to be made for integrating the library with Xcode 5.1 onwards. Thanks in advance

**Comment by pcentieiro** [comment]
Hello,

Well, I stopped working on this project some months ago, and I don’t know when I’ll get time to support it on the newest versions of Xcode…

Pedro

**Comment by guptatarun84** [comment]
Cool no issues! Let me know once you are back again on upgrading this repository. Thanks
